### ISSUE TITLE
Getting a bunch of errors I am not sure about. Please help ASAP.

### ISSUE THREAD

**Issue by MythreyanGanesh** [insidesherpa/JPMC-tech-task-2#11]
Getting a bunch of errors on the npm install and npm start part. [Attached](url
![Untitled](https://user-images.githubusercontent.com/56330768/68986987-71ba5500-07ea-11ea-9f03-52524042e3cf.png)
) 
![Untitled2](https://user-images.githubusercontent.com/56330768/68986990-7979f980-07ea-11ea-86e4-9f611a4651a3.png)

**Comment by yanga9345** [comment]
I am also getting the same error and still have not been able to resolve it.

**Comment by jbf-insidesherpa** [comment]
@MythreyanGanesh and @yanga9345 make sure you clone the repository outside of C:\\Windows\System32. Instead clone it in a place like C:\\Users\<your_account>\

Also @MythreyanGanesh , even after you've cloned the repository in C:\\Users\<your_account>\, you  still might encounter other **npm install** issues. This is because the command **python** in your system maps to python3.x. You have to make it map to python2.7.x. If you haven't installed python2.7.x yet, install it too in your system. Then map it properly in your system's path environment variable like this:
search for "environment variables" in start menu
![image](https://user-images.githubusercontent.com/54832297/69009446-2f327d00-0990-11ea-8a87-1714d1c0b92a.png)

clicking the highlighted option in the previous image should result to:
![image](https://user-images.githubusercontent.com/54832297/69009449-3a85a880-0990-11ea-9f70-dae0848c04d0.png)

edit the system environment path variable
![image](https://user-images.githubusercontent.com/54832297/69009453-407b8980-0990-11ea-9300-946f2c6767ea.png)

Make sure you have add the folder where the python2.7.x executable is located to the path
![image](https://user-images.githubusercontent.com/54832297/69009463-55f0b380-0990-11ea-9d4d-3565214a6563.png)
(ensure you temporarily remove path where python3.x executable is in the path)
(restart your cmd after and retry **python --version**; it should be 2.7.x now)

**Comment by akshatbahety** [comment]
![Screenshot (193)](https://user-images.githubusercontent.com/17676203/69148600-a6842000-0afa-11ea-8220-510e757b5a69.png)
Now it's some problem with bufferutil @jbf-insidesherpa please let me know how to solve this

**Comment by akshatbahety** [comment]
I

> 
> 
> ![Screenshot (193)](https://user-images.githubusercontent.com/17676203/69148600-a6842000-0afa-11ea-8220-510e757b5a69.png)
> Now it's some problem with bufferutil @jbf-insidesherpa please let me know how to solve this

I have installed Python 2 and set on the control panel , and have double checked everything else

**Comment by jbf-insidesherpa** [comment]
@akshatbahety based on the error you're getting it's still related to the python version issue used by npm.

![image](https://user-images.githubusercontent.com/54832297/69152012-b01b8100-0b16-11ea-8306-2ed4c05702d4.png)

We've actually [updated the setup guide](https://insidesherpa.s3.amazonaws.com/vinternships/companyassets/Sj7temL583QAYpHXD/setup_devenv_m2_v6.pdf) with more troubleshooting tips. Your issue is discussed in slide (59/91)

The suggested solution says you need to map the python command npm uses to
python 2.7.x . Here’s a [reference](https://github.com/nodejs/node-gyp#configuring-python-dependency) on how to do it.

In the setup of this task, node-gyp is called by way of npm, so in order for you to avoid the
error, you have to explicitly tell npm what python version to use. Thus, you
have to set npm's 'python' config key to the appropriate value:

`npm config set python /path/to/executable/python` 

where /path/to/executable/python is the directory where the python2.7.x binary is, for example in /usr/bin/python usually in linux/mac or C:\\Python27 for Windows

**Comment by meet1906** [comment]
npm ERR! path /home/meet/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/meet/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/meet/.npm/_logs/2020-04-23T19_27_53_866Z-debug.log

**Comment by meet1906** [comment]
What to do??

**Comment by meet1906** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/home/meet/.nvm/versions/node/v11.0.0/bin/node',
1 verbose cli   '/home/meet/.nvm/versions/node/v11.0.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v11.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bank-merge-co-task-2@0.1.0~prestart: bank-merge-co-task-2@0.1.0
6 info lifecycle bank-merge-co-task-2@0.1.0~start: bank-merge-co-task-2@0.1.0
7 verbose lifecycle bank-merge-co-task-2@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle bank-merge-co-task-2@0.1.0~start: PATH: /home/meet/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/meet/JPMC-tech-task-2-PY3/node_modules/.bin:/home/meet/.nvm/versions/node/v11.0.0/bin:/home/meet/anaconda3/bin:/home/meet/anaconda3/condabin:/home/meet/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle bank-merge-co-task-2@0.1.0~start: CWD: /home/meet/JPMC-tech-task-2-PY3
10 silly lifecycle bank-merge-co-task-2@0.1.0~start: Args: [ '-c', 'react-scripts start' ]
11 info lifecycle bank-merge-co-task-2@0.1.0~start: Failed to exec start script
12 verbose stack Error: bank-merge-co-task-2@0.1.0 start: `react-scripts start`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/home/meet/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:962:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
13 verbose pkgid bank-merge-co-task-2@0.1.0
14 verbose cwd /home/meet/JPMC-tech-task-2-PY3/datafeed
15 verbose Linux 4.15.0-54-generic
16 verbose argv "/home/meet/.nvm/versions/node/v11.0.0/bin/node" "/home/meet/.nvm/versions/node/v11.0.0/bin/npm" "start"
17 verbose node v11.0.0
18 verbose npm  v6.4.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error bank-merge-co-task-2@0.1.0 start: `react-scripts start`
23 error spawn ENOENT
24 error Failed at the bank-merge-co-task-2@0.1.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by andrew-theturtle** [comment]
![image](https://user-images.githubusercontent.com/62633701/80212012-17b39a80-867a-11ea-886a-0eca017cd173.png)
@jbf-insidesherpa Could you please help me with this? Thank you in advance

**Comment by kritikamalviya01** [comment]
code ELIFECYCLE
npm ERR! errno 1
npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MM\AppData\Roaming\npm-cache\_logs\2020-06-03T10_51_16_653Z-debug.log

**Comment by kennyklee123** [comment]
@andrew-theturtle did you end up figuring it out, I am currently in the same spot as your last post

**Comment by kennyklee123** [comment]
@jbf-insidesherpa  
![Help](https://user-images.githubusercontent.com/55815393/84583061-144eac80-ada9-11ea-8ccc-d69b8c6e9ae4.png)

I am currently stuck at this point after installing python 2.7 and setting the path to it with what you did above

**Comment by dhruvsoni365** [comment]
What is the probem here?
![Screenshot (237)](https://user-images.githubusercontent.com/56682466/89759149-23cb4700-db07-11ea-99b9-40cefcccd59e.png)
