### ISSUE TITLE
TypeError: Cannot read property 'setAttribute' of undefined

### ISSUE THREAD

**Issue by alex289799** [insidesherpa/JPMC-tech-task-2#142]
Hi Guys,
    After modifying the Graph.tsx, by pressing Start Streaming Data I've experienced the following error. Can anyone please help me with this issue? I literally got no idea on how to solve this. Thanks a lot. Really appreciate it.
![Issue 1](https://user-images.githubusercontent.com/65505315/82200515-01a29e00-98f7-11ea-94f2-d2a218e81709.jpg)

**Comment by dheerajodha** [comment]
Hi Alex, looking at your code snippet, it looks like you mistakenly deleted the line "elem.load(this.table);". Try adding this line, to line number 50 and let me know what you get.

**Comment by alex289799** [comment]
> Hi Alex, looking at your code snippet, it looks like you mistakenly deleted the line "elem.load(this.table);". Try adding this line, to line number 50 and let me know what you get.

I've tried but seems like got another error: TypeError: Cannot read property 'load' of undefined

**Comment by dheerajodha** [comment]
Can you please post a screenshot so that I can look at your full code?

**Comment by alex289799** [comment]
<img width="500" alt="1" src="https://user-images.githubusercontent.com/65505315/82343856-41e34880-99eb-11ea-92ef-238bf3241fab.png">

I had difficulties on uploading it earlier, thanks a lot.

**Comment by dheerajodha** [comment]
I'll not be able to tell what's the source of error without looking at code written before line 48.
Can you please try to post a screenshot showing most of your code?

**Comment by alex289799** [comment]
<img width="665" alt="2" src="https://user-images.githubusercontent.com/65505315/82346317-347b8d80-99ee-11ea-9a9b-ad83e2671eac.png">

I uploaded part of the script, hope this will do. Thanks.

**Comment by dheerajodha** [comment]
Oh okay, so clearly you have a problem with variable "perspective".
I'm not sure what causes that error, so I'm attaching my Graph.tsx file below, please have a look and try to find the error in your code(if any).

If the error still persists, please upload your file in your next comment. (To upload a file in GitHUb comment, you just need to drag the file and drop it in comment section, it will then upload automatically. Oh and you can't add .tsx file here, so copy that code and paste it into a .txt file and upload that file instead)

[Test_Graph.txt](https://github.com/insidesherpa/JPMC-tech-task-2/files/4651651/Test_Graph.txt)

**Comment by alex289799** [comment]
Hi thank you so much for your text...however, I did double check but still cannot seem to find the error..I've uploaded mine.

[Graph Txt.txt](https://github.com/insidesherpa/JPMC-tech-task-2/files/4651824/Graph.Txt.txt)

**Comment by dheerajodha** [comment]
So I found a mismatch :
Line 35 : instead of "perspective.viewer" is it "perspective-viewer".
Line 64 : Press SpaceBar 2 times before the componentDidUpdate() to align it with the "}" in above line. However, I'm not sure whether tab spacing is relevant in .tsx files or not but try.

If it still, doesn't solve your problem, start over.
Delete your project, reclone it, go into that folder where you cloned, and follow everything as described in InsideSherpa's file.
Please make sure that when you run "npm install" and "npm start" using your CMD/Terminal, you are **inside** the folder where you cloned your project!

If the problem still persists, post the error message here again, we can try and solve it out.

**Comment by alex289799** [comment]
Hi, first of all, thank you so much for the help! I got it right after changing it to "perspective-viewer". However, I got it stuck again when creating the patch file. Can you please help me to look at it? Thank you.

![3](https://user-images.githubusercontent.com/65505315/82367946-7ddad580-9a0c-11ea-9804-f664cc5fcce0.jpg)

**Comment by dheerajodha** [comment]
No problem, it's my pleasure :)

So, now you're getting a very standard error : 'xyz' is not recognized as an internal or external command.
The problem here is maybe git is installed in your system somewhere (right? If not, then install it first), but when you run any command in your CMD starting with 'git' your CMD has no idea what 'git' is, so now your aim is to introduce 'git' files to your CMD.
You can do that by first, finding out where in your PC the GIT files are located. Copy that location and correctly append that in your PATH (PATH is something very sensitive, so make sure you don't mess anything there while adding).
You got the basic idea right? So have a look here : https://stackoverflow.com/questions/4492979/git-is-not-recognized-as-an-internal-or-external-command

If you get some more errors, then post your error screenshots here.

**Comment by alex289799** [comment]
Hi, I went through the link where I understood my mistakes. I have finally completed the course. Really really appreciate all your help!

**Comment by dheerajodha** [comment]
I'm really happy to know that! You're welcome!
Please close this issue, thanks!
