### ISSUE TITLE
NPM Not starting

### ISSUE THREAD

**Issue by ssreddyboppidi** [insidesherpa/JPMC-tech-task-2#144]
sboppidi@Sanjeevs ~ % npm start  
npm ERR! path /Users/sboppidi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/sboppidi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sboppidi/.npm/_logs/2020-05-18T15_03_54_906Z-debug.log

**Comment by dheerajodha** [comment]
Hello, it seems that you're running the "npm start" command in the folder which doesn't contain **package.json** file.

You can try to run this same command **inside** your cloned project folder "JPMC-tech-task-2", then it might work.

**Comment by alishabhi** [comment]
Hello im using windows 7 and Python 2.7.17. my npm install command was run wihout any vulnerabilities but npm start command is not working . im attaching a snip of cmd prompt. can you help me with this?
![query](https://user-images.githubusercontent.com/66030235/83054578-46a19f80-a070-11ea-9e06-14886ff99519.PNG)

**Comment by alishabhi** [comment]
[2020-05-27T18_12_47_288Z-debug.log](https://github.com/insidesherpa/JPMC-tech-task-2/files/4690907/2020-05-27T18_12_47_288Z-debug.log)
also when i changed the directory to JPMC-tech-task-2, I got the above output. Please someone help me as I am stuck at the very last step of starting the task and I have been trying hard since my system is windows 7

**Comment by dheerajodha** [comment]
Hi @alishabhi yes sure!
See even though you have 0 vulnerablities while running npm install, but if you look at the description it says "no such file or directory". So, basically your terminal is searching for package.json inside the folder "Dell"  but it doesn't have that.
So, if you notice you can see a "package.json" inside your "JPMC-tech-task" folder. so you need to go into that path **and then** "npm install" followed by "npm start".

It makes sense to think like this : 
- What does "npm install" do? It installs all the project-related dependencies.
- How does it know which dependencies to install? They are clearly mention inside package.json
- What if you run "npm install" inside a folder which doesn't have package.json? "npm install" won't run because it doesn't know what to install.
- What if "npm install" doesn't run successfully? Since the dependencies have not been installed, we won't be able to start our project!

Finally if it still shows some errors then post them here, I'll try my best to solve them.

**Comment by alishabhi** [comment]
@dheerajodha thanks for the help but as I said even after changing the directory it is showing error im attaching whole output here... also I tried installing required tools and configurations of python by executing "npm install --global --production windows-build-tools"(for node-gyp) as I am not able to install Visual Studio Build TOols because of system incompetency (windows 7 without .NET framework) but that also threw an error! please help!
![1](https://user-images.githubusercontent.com/66030235/83060695-8325c900-a079-11ea-9517-1ea11fd22925.PNG)
![2](https://user-images.githubusercontent.com/66030235/83060689-815c0580-a079-11ea-8d32-a4e5d2e31b81.PNG)
![3](https://user-images.githubusercontent.com/66030235/83060691-828d3280-a079-11ea-86c8-a318126da7ee.PNG)

error in node-gyp
![g1](https://user-images.githubusercontent.com/66030235/83061125-1b23b280-a07a-11ea-989c-d2ec9c78d41f.PNG)
![g2](https://user-images.githubusercontent.com/66030235/83061129-1c54df80-a07a-11ea-982c-7b7ecf5e8551.PNG)

**Comment by dheerajodha** [comment]
Oh okay, please try this and let me know what you get : 
Run this command from an **administrative** **shell** to install the "software" dependencias (Visual Studio, Python) on windows:

npm install --global --production windows-build-tools

npm install -g node-gyp

npm install

npm start

Note : Execute these commands from inside the project folder where you cloned your JPMC project.

**Comment by alishabhi** [comment]
I ran the commands given by you in PowerShell (admin)
![s1](https://user-images.githubusercontent.com/66030235/83147044-c7b27280-a114-11ea-93db-7f708b3b1d97.PNG)
..here it is getting stuck.

**Comment by alishabhi** [comment]
@dheerajodha Can you please help me with this? I really want to start this task...

**Comment by dheerajodha** [comment]
Hi @alishabhi sorry for being inactive, don't worry maybe we can solve this.
Reading your previous errors, do you Visual Studio in your PC/Laptop ? 
- If not, then please install the latest version from the official site and then just run "npm install". 
- If you have it already, let me know.

If you get errors, then post them below. And I hope you are using "v11.0.0" version of node (to check, type node --version).
