### ISSUE TITLE
Patch File size exceeded

### ISSUE THREAD

**Issue by skyhawkbs01** [insidesherpa/JPMC-tech-task-2#149]
Please tell what to do as my patch file size is 310MB and allowed size is 250MB.!!

**Comment by dheerajodha** [comment]
Hi @skyhawkbs01 , my file size is 450MB and I was able to successfully create a patch file.
Can you please post the screenshot of the error message you are getting?

**Comment by skyhawkbs01** [comment]
On the submission page its displaying that the allowed size is 250MB, as the patch file I created was of 310MB.

**Comment by dheerajodha** [comment]
Oh I'm sorry 450MB is the size of my whole folder not the patch file.
My patch file is of around 6KB, as it should be.
A patch can be even more than 1MB since it's just a normal file containing texts, so you are going wrong somewhere, are you sure you executed right commands as listed in the InsideSherpa document, to create a patch file ?
git add -A
git config user.email "<your_email_address>"
git config user.name "<your_name>"
git commit -m 'Create Patch File'
git format-patch -1 HEAD

 If so, does your final output says **001-Create-Patch-File.patch** ? And are you uploading **only** the "001-Create-Patch-File.patch" file right?

**Comment by skyhawkbs01** [comment]
Sir I'll try once more.
Thanks

**Comment by dheerajodha** [comment]
Yes sure, let me know if you get any further error.
And if you successfully upload your patch file then please close this issue!
