### ISSUE TITLE
Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

### ISSUE THREAD

**Issue by Octaviusalk** [insidesherpa/JPMC-tech-task-2#16]
When I try to launch the application on npm start, I get the error: Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

**Comment by jbf-insidesherpa** [comment]
@Octaviusalk your npm install most likely had errors. Please double check. Then based on the errors you get, please check if any of the troubleshooting slides in the setup guide answer your problem. If not leave details/screenshots on the error(s) you're getting on the terminal and browser

**Comment by jbf-insidesherpa** [comment]
@Octaviusalk I'm closing this issue now since it's been a while. Feel free to re-open if necessary

**Comment by tanay-nagarsheth** [comment]
Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307
My npm is installed rightly yet it wont stop showing this error, please help

**Comment by deeksha207** [comment]
sir i have also that problem, i tried a a lot to resolve this problem
![plzres](https://user-images.githubusercontent.com/54803390/81490484-801c9180-92a0-11ea-910f-fff603381786.png)

**Comment by deeksha207** [comment]
plz sir help me to figureout this

**Comment by richasingh15** [comment]
You can download node_modules from @jpmorgan Task set up  from and replace the existing node modules with the new one. It will work!

**Comment by deeksha207** [comment]
![bank](https://user-images.githubusercontent.com/54803390/81640602-93646400-943c-11ea-8b8a-db8026d87a9c.png)
mam its working but now this error comes????
mam i tried to comlete this task from 2 days but didn't get any solution

**Comment by deeksha207** [comment]
ma'am plz help me this to figure out ?
and thanks to reply on my previous doubt :-)

**Comment by deeksha207** [comment]
can anyone suggest any solution

**Comment by SurajPatidar201198** [comment]
@deeksha207 how you solved your error?

**Comment by bhanu3509** [comment]
The issue will be resolved if you install the modules mentioned in the package.json separately in another command prompt(not in the JPMC directory). After installing the mentioned packages using npm install from the second command line. You will have to check, the node_modules folder in JPMC and copy the modules you have installed now(from your root directory ) into the JPMC directory. And this is the important step now, you will have to remove the dependencies in package.json file before proceeding. Then, if you have followed above mentioned steps perfectly, your'e good to go now. You can now run the npm start command. 

**Remember, you cannot run the npm install command from the JPMC-tech-task-2 directory, because it'll keep on removing and reinstalling the same packages again and again and you'll keep getting the errors. So, just do as i have mentioned above and you'll succeed in completing your task. You can copy the same modules for task3 also.**

NOTE:- I'll upload these packages in my repository (github :- @bhanu3509) in case you can't follow the above mentioned steps. Good luck with the task :-)
