### ISSUE TITLE
Failed to compile; Graph.tsx ; Unexpected token

### ISSUE THREAD

**Issue by RushaliMahajan** [insidesherpa/JPMC-tech-task-2#166]
Please help me resolve this issue.

![image](https://user-images.githubusercontent.com/44033857/82637398-53626580-9c22-11ea-9daa-8bbcfaa02787.png)

**Comment by dheerajodha** [comment]
Hello @RushaliMahajan in order to solve your issue, can you please provide full details like : 
-Your OS, python version
-After running which command you got this error?

Also, in windows if your path contains some [space] then it may cause some problems, you might need to consider changing you folder name from "Rushali Mahajan" to "Rushali Mahajan". Thanks!

**Comment by RushaliMahajan** [comment]
My OS is Windows 10* 64-bit.
Python 3.7.4

Everything was working fine even after making desired changes in App.tsx, however after i added more attributes to the element in Graph.tsx, it started showing this error.
The error points at 'export default Graph', but it didnt showed error at 'export default App', i dont know why.

**Comment by RushaliMahajan** [comment]
This is my Graph.tsx
![2020-05-22 (2)](https://user-images.githubusercontent.com/44033857/82671279-38144c00-9c5c-11ea-8a49-3673adca5b2f.png)
![2020-05-22 (4)](https://user-images.githubusercontent.com/44033857/82671334-4e220c80-9c5c-11ea-923f-3544f8d00418.png)
![2020-05-22 (5)](https://user-images.githubusercontent.com/44033857/82671358-55e1b100-9c5c-11ea-86a2-ac94f38d978c.png)

**Comment by dheerajodha** [comment]
Hi @RushaliMahajan first of all can you please change your path as I mentioned in my previous comment, I'm saying this because sometimes the main cause of error is the path while we look for solution in all the different places.

Now, please replace your line 57 to 61 with the code inside the
[code.txt](https://github.com/insidesherpa/JPMC-tech-task-2/files/4668940/code.txt)
 attached file.

The difference is just of this symbol ->  **``** 

If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!

**Comment by RushaliMahajan** [comment]
I made the changes you suggested and also changed my path, unfortunately still getting the same error.
![abc](https://user-images.githubusercontent.com/44033857/82697367-6a3aa380-9c86-11ea-8c0f-afd4923680a6.png)

also if i remove the export statement, it shows the same error pointing at nothing
![def](https://user-images.githubusercontent.com/44033857/82697416-88a09f00-9c86-11ea-88be-2e389b9c0371.png)

**Comment by dheerajodha** [comment]
@RushaliMahajan Oh okay, please give this a shot : https://stackoverflow.com/a/41319564 and let me know what you get.

**Comment by RushaliMahajan** [comment]
@dheerajodha  it worked!! Thank you soo much!!

**Comment by dheerajodha** [comment]
Glad to know @RushaliMahajan  you must know what the problem was, so your sublime didn't know what are .tsx files, as noticeable from the fact that in your .tsx files the colour schemes are not working so that was a good clue to solve the problem. Happy coding!
