### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by sm2772ms** [insidesherpa/JPMC-tech-task-2#169]
<img width="1280" alt="Screenshot 2020-05-23 at 14 15 26" src="https://user-images.githubusercontent.com/65816678/82731582-f0470080-9cff-11ea-8811-9cd0adb8d4af.png">

**Comment by sm2772ms** [comment]
Stuck at this stage, don't understand what the npm WARN, or ERR! mean, or how to fix them.

**Comment by dheerajodha** [comment]
Hello @sm2772ms you are supposed execute all these commands **INSIDE** the directory where you cloned your project called "JPMC-tech-task-xyz". 

If you get any errors after that, then post here. If it works well kindly close this issue, thanks!

**Comment by sm2772ms** [comment]
Hey

Is that directory this? Sorry really not familiar with coding.

**Comment by dheerajodha** [comment]
I'm not sure if I understood which directory you are referring too. Also, I'm not familiar with Mac haha but no problem! So you must've cloned the JPMC task project right using the git clone command?
Currently your terminal points to "samuelmutto$" because you have opened terminal (or it opens here by default) from inside the folder called "samuelmutto" so you need to change this path first.

- You need to go inside that folder and open your terminal from that folder.
- Then you run "npm install"
- Then "npm start"

Please let me know if you get stuck anywhere or get confused.

**Comment by sm2772ms** [comment]
Yes it worked, thank you so much!!

**Comment by dheerajodha** [comment]
That's great! can you please close this issue?

**Comment by sm2772ms** [comment]
Sorry to ask another question

Regarding the app.tsx,
How do you access it to make the changes on visual studio??

Sent from Samuel Mutto

On 23 May 2020, at 16:03, Dheeraj Singh Jodha <notifications@github.com> wrote:

﻿

That's great! can you please close this issue?

**Comment by dheerajodha** [comment]
No it's totally fine!

So what I understood from your questions is that you are asking how can you open your app.tsx on Visual Studio Code to edit it. If that's right then you have to open Visual Studio and click on "open folder" and select your cloned project folder which should be named "JPMC-tech-task-xyz" and then your whole folder will be available inside your Visual studio so then you can easily open your app.tsx file and edit it.

Let me know if I got it wrong.

**Comment by sm2772ms** [comment]
Yeah that worked, once again thank you so much

**Comment by sm2772ms** [comment]
Yeah it worked, thank you so much again

**Comment by dheerajodha** [comment]
No problem!
