### ISSUE TITLE
NPM START

### ISSUE THREAD

**Issue by PhilipOlabisi** [insidesherpa/JPMC-tech-task-2#17]
C:\Users\admin>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2019-12-04T02_52_10_715Z-debug.log

**Comment by jbf-insidesherpa** [comment]
@PhilipOlabisi the reason you're getting that error is because you're trying to execute the commands outside the repository. You should be in the repository first before you execute any command. The setup guide discusses how to do this i.e. using the **cd** command. Please read thru the instructions thoroughly. Once you're in the repository via the command line, please redo commands again i.e. **npm install** and **npm start**

Closing this issue now. Feel free to reopen if necessary

**Comment by PhilipOlabisi** [comment]
Resolved. Thank you
