### ISSUE TITLE
[python3] cannot find module error when running npm start

### ISSUE THREAD

**Issue by neilmp2** [insidesherpa/JPMC-tech-task-2#29]
I had to manually download node_modules. Running npm start gives the errors (image attached). 
OS: Win 10 
I checked that the version for nvm is 11.0.0. 
![image](https://user-images.githubusercontent.com/46456208/76991994-86cdfe80-6918-11ea-8009-965c5e9aa3ae.png)

**Comment by jbf-insidesherpa** [comment]
@neilmp2 have you managed to get it to work on your end?

**Comment by parthshuklaa-me** [comment]
I am struggling so much with setting up the environment! The nvm install as well as nvm start commands are showing errors!

![image](https://user-images.githubusercontent.com/57247572/77302150-e82a0f00-6d16-11ea-8ef5-8fdbffe7a31b.png)

**Comment by jbf-insidesherpa** [comment]
@parthshuklaa-me the reason you're getting that issue is because your command line / terminal is not inside the repository that you (should've) cloned. 

If you notice, your screenshot tells you that you're in \Users\HP-pc

If you cloned the repo in HP-pc you'll be able to go inside it by doing 
**cd \Users\HP-pc\JPMC-tech-task-2** 
(if the repo is located elsewhere, the command should be similar just change the path to the right one)

Then that's point where you can execute the **npm** commands.

**Comment by Udit3008** [comment]
still not working @jbf-insidesherpa 
please help me!!
![Screenshot (208)](https://user-images.githubusercontent.com/43252805/82240462-15322100-9958-11ea-8f57-1ba428b3b738.png)

**Comment by ibrostar** [comment]
@Udit3008 Did you manage to solve the issue ? i have the same problem thanks.

**Comment by neilmp2** [comment]
Replacing the npm_modules folder with the one linked to in the troubleshooting guide worked for me.

**Comment by neilmp2** [comment]
@ibrostar 
Make sure you're in the right directory, when you run the npm commands. The package.json file is generated in the directory with all the project files. In Udit's screenshot, he is not at the correct directory (and so there is no package.json file in system32/users).
