### ISSUE TITLE
NPM install and start issue

### ISSUE THREAD

**Issue by skimtsg** [insidesherpa/JPMC-tech-task-2#32]
Hi,
I have done all the steps for installing the Visual Studio Installer, i have successfully downloaded the program in my computer. I am at the last step where I'm supposed to launch the npm ( when i have to type npm install and npm start). I get this when I try installing npm. 
![2020-04-01](https://user-images.githubusercontent.com/62951088/78106849-352f7480-73ec-11ea-8baa-95212e8e5e1b.png)

**Comment by jbf-insidesherpa** [comment]
@skimtsg the reason none of the npm commands are working for you is because you're in the wrong directory

Notice that you're in C:\Program Files (x86) ... 

You need to be in the repository that you cloned. i.e. JPMC-tech-task-2

The setup guide already discusses this. You have to **cd** into that directory wherever it is that you run the **git clone command**
