### ISSUE TITLE
the user location is not recognized as internal or external command

### ISSUE THREAD

**Issue by Aanchal116** [insidesherpa/JPMC-tech-task-2#73]
![Screenshot (13)](https://user-images.githubusercontent.com/48170750/81189784-9e4e6d00-8fd4-11ea-8ec4-74b5d75bfd3d.png)

**Comment by SHREYASH-MUKESH** [comment]
try to run nvm use v11.0.0 inside the directory in which u have download the task git hub file(JPMC-tech-task-2-PY3 or may be the other one whatever you are using)

**Comment by prakharindoria** [comment]
See Solution thread by me.

**Comment by prakharindoria** [comment]
The solution thread for the same will help resolving this issue. It is already there.

**Comment by dheerajodha** [comment]
Hi @Aanchal116 you are getting this error because your path name has space between it (ie. "**krishan pahal**"). So, as suggested above, go to the folder where you cloned your project, and repeat the same commands again.

If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!
