### ISSUE TITLE
JP Morgan Chase Task 2: Use JPMorgan Chase frameworks and tools

### ISSUE THREAD

**Issue by gemmaf97** [insidesherpa/JPMC-tech-task-2#8]
Hello, I am currently doing the JPMorgan Chase Software Engineering Virtual Experience and am given these sets of instructions. 
[setup_devenv_m2_v4.pdf](https://github.com/insidesherpa/JPMC-tech-task-2/files/3802244/setup_devenv_m2_v4.pdf)
I am currently on page 18/64 where i had to start the client application, running the commands below: 
npm install
npm start

The page it should've reached me was: 
![Screenshot 2019-11-03 at 22 46 49](https://user-images.githubusercontent.com/57332580/68093326-70089d00-fe8c-11e9-9f00-ff6451924ef5.png)
as demonstrated by page 19/64, but I couldn't access that window. I am just struggling with the final parts of this work. Please, can you help me? I have attached a screenshot of my terminal window to see where I have gone wrong: 
![Screenshot 2019-11-03 at 22 47 05](https://user-images.githubusercontent.com/57332580/68093363-d42b6100-fe8c-11e9-8d2f-78eda9c62506.png)

Thank you so much. 

Gemma

**Comment by jbf-insidesherpa** [comment]
@gemmaf97 have you resolved your issue? I think it's just because the current working directory of your terminal is not inside the repository folder. You're supposed to execute the commands (e.g. `npm install` and `npm start`) when your terminal's current working directory is in the repository. For that to happen after cloning the repo you're supposed to **cd** (aka change directory) into the repo like `cd JPMC-tech-task2` For more info on how to use cd, check this out: https://www.macworld.com/article/2042378/master-the-command-line-navigating-files-and-folders.html 

Hope this helps
