### ISSUE TITLE
Server application stuck. CMD doesn't respond.

### ISSUE THREAD

**Issue by IFHAM99** [insidesherpa/JPMC-tech-task-2#86]
![Capture](https://user-images.githubusercontent.com/50768671/81460586-eb446600-91c3-11ea-8edf-f5e64036ca7e.PNG)

**Comment by dheerajodha** [comment]
Hi @IFHAM99 server is not stuck, it's working under the hood, so that's why you're not able to type anything.

However I'm not sure what your error is, so can you more specific regarding what exactly is stopping you from completing this task?
If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!

**Comment by IFHAM99** [comment]
The issue is resolved, thanks.
